<a href="https://colab.research.google.com/github/rxhith/NLP/blob/main/Nlpexp4_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Define a list of categorical labels
labels = ['dog', 'cat', 'bird', 'cat', 'dog', 'bird']

# Create a OneHotEncoder object
encoder = OneHotEncoder()

# Fit the encoder to the labels and transform the labels
onehot = encoder.fit_transform(np.array(labels).reshape(-1, 1)).toarray()

# Print the OneHot encoded labels
print(onehot)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [ ]:
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist

# Load a script as a string
script = "This is a sample script. It contains multiple words that we want to count."

# Tokenize the script into individual words
words = word_tokenize(script)

# Compute the frequency distribution of the words
freq_dist = FreqDist(words)

# Print the 10 most common words in the script
print(freq_dist.most_common(10))

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


[('.', 2), ('This', 1), ('is', 1), ('a', 1), ('sample', 1), ('script', 1), ('It', 1), ('contains', 1), ('multiple', 1), ('words', 1)]


In [ ]:
import nltk
from nltk.tokenize import word_tokenize

# Load a script as a string
script = "This is a sample script. It contains multiple words that we want to filter out, like 'a' and 'the'."

# Tokenize the script into individual words
words = word_tokenize(script)

# Define the words to filter out
stopwords = ['a', 'an', 'the']

# Create a list of words that don't match the filter words
filtered_words = [word for word in words if word.lower() not in stopwords]

# Join the filtered words back into a string
filtered_script = ' '.join(filtered_words)

# Print out the filtered script
print(filtered_script)

This is sample script . It contains multiple words that we want to filter out , like ' ' and 'the ' .


In [ ]:
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize

# Load a script as a string
script = "This is a complete sentence. This sentence is incomplete"

# Tokenize the script into sentences
sentences = sent_tokenize(script)

# Check for incomplete sentences
for sentence in sentences:
    words = word_tokenize(sentence)
    if words[-1] != '.':
        print(f"Incomplete sentence: {sentence}")

Incomplete sentence: This sentence is incomplete


In [ ]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')


text = input("Enter a sentence: ")
tokens = nltk.word_tokenize(text)
print(tokens)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


Enter a sentence: Hi hello how
['Hi', 'hello', 'how']


In [ ]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
nltk.download('punkt')
nltk.download('stopwords')

text = input("Enter a sentence: ")
tokens = word_tokenize(text)
stop_words = set(stopwords.words('english'))
filtered_tokens = [token for token in tokens if token.lower() not in stop_words]
print(filtered_tokens)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


Enter a sentence: I want to buy an apple phone, but I cannot even buy a regular apple.
['want', 'buy', 'apple', 'phone', ',', 'even', 'buy', 'regular', 'apple', '.']


In [ ]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
nltk.download('punkt')

text = input("Enter a sentence: ")
tokens = word_tokenize(text)
stemmer = PorterStemmer()
stemmed_tokens = [stemmer.stem(token) for token in tokens]
print(stemmed_tokens)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


Enter a sentence: I could not attend your calls as I was busy gaming.
['i', 'could', 'not', 'attend', 'your', 'call', 'as', 'i', 'wa', 'busi', 'game', '.']
